Medhansh Gupta - 25070123074

Experiment-14: Data Binning and Data Formatting using Python

In [2]:
import pandas as pd
import numpy as np
data = {
    'Product' : ['laptop','mobile','tablet','headphones','smartwatch','camera'],
    'Price' : [55000,20000,30000,2000,8000,45000],
    'Units_Sold' : [25,60,35,80,50,15]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      laptop  55000          25
1      mobile  20000          60
2      tablet  30000          35
3  headphones   2000          80
4  smartwatch   8000          50
5      camera  45000          15

In [3]:
# Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      laptop  55000          25           High
1      mobile  20000          60         Medium
2      tablet  30000          35         Medium
3  headphones   2000          80            Low
4  smartwatch   8000          50            Low
5      camera  45000          15           High

In [4]:
# Data Binning units sold
bins2 = [0,30,60,100]
labels2 = ['Low','Medium','High']
df['Units_Sold_Category'] = pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      laptop  55000          25           High                 Low
1      mobile  20000          60         Medium              Medium
2      tablet  30000          35         Medium              Medium
3  headphones   2000          80            Low                High
4  smartwatch   8000          50            Low              Medium
5      camera  45000          15           High                 Low

In [9]:
# convert data type
print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)
df

Product                  object
Price                     int64
Units_Sold              float64
Price_Category         category
Units_Sold_Category    category
dtype: object
Product                  object
Price                     int64
Units_Sold              float64
Price_Category         category
Units_Sold_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      laptop  55000        25.0           High                 Low
1      mobile  20000        60.0         Medium              Medium
2      tablet  30000        35.0         Medium              Medium
3  headphones   2000        80.0            Low                High
4  smartwatch   8000        50.0            Low              Medium
5      camera  45000        15.0           High                 Low

In [10]:
#convert text to uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
5      CAMERA  45000        15.0           High                 Low

In [11]:
#Rounding Values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
5      CAMERA  45000        15.0           High                 Low

In [13]:
#additional operations
#sort data
df.sort_values(by='Price',inplace = True)
df

      Product  Price  Units_Sold Price_Category Units_Sold_Category
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
5      CAMERA  45000        15.0           High                 Low
0      LAPTOP  55000        25.0           High                 Low

In [14]:
df.sort_values(by='Price',ascending = False,inplace = True)
df

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
5      CAMERA  45000        15.0           High                 Low
2      TABLET  30000        35.0         Medium              Medium
1      MOBILE  20000        60.0         Medium              Medium
4  SMARTWATCH   8000        50.0            Low              Medium
3  HEADPHONES   2000        80.0            Low                High

In [15]:
#display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [16]:
# Dataset :  Food Delivery Orders
import pandas as pd
import numpy as np
data = {
    'Order_ID' : ['01','02','03','04','05','06','07','08'],
    'Order_Value' : [250,450,120,600,300,150,500,220],
    'Delivery_Time' : [30,45,25,60,35,20,50,28],
    'Delivery_km' : [5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Delivery_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [17]:
#Binning Order Value
bins = [0,200,400,700]
labels = ['Low Order','Medium Order','High Order']
df['Order_Value_Category'] = pd.cut(df['Order_Value'],bins=bins,labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Delivery_km Order_Value_Category
0       01          250             30            5         Medium Order
1       02          450             45            8           High Order
2       03          120             25            3            Low Order
3       04          600             60           10           High Order
4       05          300             35            6         Medium Order
5       06          150             20            2            Low Order
6       07          500             50            9           High Order
7       08          220             28            4         Medium Order

In [20]:
# Binning Delivery Time
bins2 = [0,30,45,70]
labels2 = ['Fast ','Normal','Slow ']
df['Delivery_Speed'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Delivery_km Order_Value_Category  \
0       01          250             30            5         Medium Order
1       02          450             45            8           High Order
2       03          120             25            3            Low Order
3       04          600             60           10           High Order
4       05          300             35            6         Medium Order
5       06          150             20            2            Low Order
6       07          500             50            9           High Order
7       08          220             28            4         Medium Order

  Delivery_Time_Category Delivery_Speed
0                  Fast           Fast
1                 Normal         Normal
2                  Fast           Fast
3                  Slow           Slow
4                 Normal         Normal
5                  Fast           Fast
6                  Slow           Slow
7                  Fast           Fast

In [21]:
# Binning Delivery km
bins3 = [0,3,5,10]
labels3 = ['Short ','Medium','Long']
df['Delivery_Distance'] = pd.cut(df['Delivery_km'],bins=bins3,labels=labels3)
print(df)

  Order_ID  Order_Value  Delivery_Time  Delivery_km Order_Value_Category  \
0       01          250             30            5         Medium Order
1       02          450             45            8           High Order
2       03          120             25            3            Low Order
3       04          600             60           10           High Order
4       05          300             35            6         Medium Order
5       06          150             20            2            Low Order
6       07          500             50            9           High Order
7       08          220             28            4         Medium Order

  Delivery_Time_Category Delivery_Speed Delivery_Distance
0                  Fast           Fast             Medium
1                 Normal         Normal              Long
2                  Fast           Fast             Short
3                  Slow           Slow               Long
4                 Normal         Normal              Long
5                  Fast           Fast             Short
6                  Slow           Slow               Long
7                  Fast           Fast             Medium

In [22]:
# Count of categories
print(df['Order_Value_Category'].value_counts())
df

Order_Value_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Delivery_km,Order_Value_Category,Delivery_Time_Category,Delivery_Speed,Delivery_Distance
0,01,250,30,5,Medium Order,Fast,Fast,Medium
1,02,450,45,8,High Order,Normal,Normal,Long
2,03,120,25,3,Low Order,Fast,Fast,Short
3,04,600,60,10,High Order,Slow,Slow,Long
4,05,300,35,6,Medium Order,Normal,Normal,Long
5,06,150,20,2,Low Order,Fast,Fast,Short
6,07,500,50,9,High Order,Slow,Slow,Long
7,08,220,28,4,Medium Order,Fast,Fast,Medium

In [24]:
# Convert Order_ID to Uppercase
df['Order_ID'] = df['Order_ID'].str.upper()
print(df)

  Order_ID  Order_Value  Delivery_Time  Delivery_km Order_Value_Category  \
0       01          250             30            5         Medium Order
1       02          450             45            8           High Order
2       03          120             25            3            Low Order
3       04          600             60           10           High Order
4       05          300             35            6         Medium Order
5       06          150             20            2            Low Order
6       07          500             50            9           High Order
7       08          220             28            4         Medium Order

  Delivery_Time_Category Delivery_Speed Delivery_Distance
0                  Fast           Fast             Medium
1                 Normal         Normal              Long
2                  Fast           Fast             Short
3                  Slow           Slow               Long
4                 Normal         Normal              Long
5                  Fast           Fast             Short
6                  Slow           Slow               Long
7                  Fast           Fast             Medium